languageCode = "en-us"
title = "Han Tuzun"
theme = "hanworthy"
enableRobotsTXT = true
paginate = 7 # Set the number of posts to show before overflowing to the next page.

[taxonomies]
  series = "series"
  tag = "tags"

[author]
	name = "hantuzun"

# Set to false to disallow raw HTML in markdown files
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[frontmatter]
date = ["date"]
lastmod = ["lastmod"]

[params]
	math = true
  showReadMore = false

# Menu links along the sidebar navigation.
[[menu.main]]
	name = "Subscribe"
	identifier = "subscribe"
	url = "https://hantuzun.substack.com/subscribe/"
	weight = 1
[[menu.main]]
  name = "Twitter"
  identifier = "twitter"
  url = "https://twitter.com/0xTuzun/"
  weight = 2

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.twitter]
    disable = false
    enableDNT = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
